<?php
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'pear2\\windowsazure\\core\\httpclient' => '/WindowsAzure/Core/HttpClient.php',
            'pear2\\windowsazure\\core\\ihttpclient' => '/WindowsAzure/Core/IHttpClient.php',
            'pear2\\windowsazure\\core\\invalidargumenttypeexception' => '/WindowsAzure/Core/InvalidArgumentTypeException.php',
            'pear2\\windowsazure\\core\\iservicefilter' => '/WindowsAzure/Core/IServiceFilter.php',
            'pear2\\windowsazure\\core\\iurl' => '/WindowsAzure/Core/IUrl.php',
            'pear2\\windowsazure\\core\\serviceexception' => '/WindowsAzure/Core/ServiceException.php',
            'pear2\\windowsazure\\core\\url' => '/WindowsAzure/Core/Url.php',
            'pear2\\windowsazure\\core\\windowsazureutilities' => '/WindowsAzure/Core/WindowsAzureUtilities.php',
            'pear2\\windowsazure\\logger' => '/WindowsAzure/Logger.php',
            'pear2\\windowsazure\\resources' => '/WindowsAzure/Resources.php',
            'pear2\\windowsazure\\services\\blob\\blobrestproxy' => '/WindowsAzure/Services/Blob/BlobRestProxy.php',
            'pear2\\windowsazure\\services\\blob\\blobservice' => '/WindowsAzure/Services/Blob/BlobService.php',
            'pear2\\windowsazure\\services\\blob\\blobsettings' => '/WindowsAzure/Services/Blob/BlobSettings.php',
            'pear2\\windowsazure\\services\\blob\\iblob' => '/WindowsAzure/Services/Blob/IBlob.php',
            'pear2\\windowsazure\\services\\blob\\models\\accesscondition' => '/WindowsAzure/Services/Blob/Models/AccessCondition.php',
            'pear2\\windowsazure\\services\\blob\\models\\accessconditionheadertype' => '/WindowsAzure/Services/Blob/Models/AccessConditionHeaderType.php',
            'pear2\\windowsazure\\services\\blob\\models\\accesspolicy' => '/WindowsAzure/Services/Blob/Models/AccessPolicy.php',
            'pear2\\windowsazure\\services\\blob\\models\\acquireleaseoptions' => '/WindowsAzure/Services/Blob/Models/AcquireLeaseOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\acquireleaseresult' => '/WindowsAzure/Services/Blob/Models/AcquireLeaseResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\blob' => '/WindowsAzure/Services/Blob/Models/Blob.php',
            'pear2\\windowsazure\\services\\blob\\models\\blobprefix' => '/WindowsAzure/Services/Blob/Models/BlobPrefix.php',
            'pear2\\windowsazure\\services\\blob\\models\\blobproperties' => '/WindowsAzure/Services/Blob/Models/BlobProperties.php',
            'pear2\\windowsazure\\services\\blob\\models\\blobserviceoptions' => '/WindowsAzure/Services/Blob/Models/BlobServiceOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\blobtype' => '/WindowsAzure/Services/Blob/Models/BlobType.php',
            'pear2\\windowsazure\\services\\blob\\models\\container' => '/WindowsAzure/Services/Blob/Models/Container.php',
            'pear2\\windowsazure\\services\\blob\\models\\containeracl' => '/WindowsAzure/Services/Blob/Models/ContainerACL.php',
            'pear2\\windowsazure\\services\\blob\\models\\containerproperties' => '/WindowsAzure/Services/Blob/Models/ContainerProperties.php',
            'pear2\\windowsazure\\services\\blob\\models\\createbloboptions' => '/WindowsAzure/Services/Blob/Models/CreateBlobOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\createblobpagesoptions' => '/WindowsAzure/Services/Blob/Models/CreateBlobPagesOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\createblobpagesresult' => '/WindowsAzure/Services/Blob/Models/CreateBlobPagesResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\createcontaineroptions' => '/WindowsAzure/Services/Blob/Models/CreateContainerOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\deletebloboptions' => '/WindowsAzure/Services/Blob/Models/DeleteBlobOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\getblobmetadataoptions' => '/WindowsAzure/Services/Blob/Models/GetBlobMetadataOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\getblobmetadataresult' => '/WindowsAzure/Services/Blob/Models/GetBlobMetadataResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\getbloboptions' => '/WindowsAzure/Services/Blob/Models/GetBlobOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\getblobpropertiesoptions' => '/WindowsAzure/Services/Blob/Models/GetBlobPropertiesOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\getblobpropertiesresult' => '/WindowsAzure/Services/Blob/Models/GetBlobPropertiesResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\getblobresult' => '/WindowsAzure/Services/Blob/Models/GetBlobResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\getcontaineraclresult' => '/WindowsAzure/Services/Blob/Models/GetContainerACLResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\getcontainerpropertiesresult' => '/WindowsAzure/Services/Blob/Models/GetContainerPropertiesResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\leasemode' => '/WindowsAzure/Services/Blob/Models/LeaseMode.php',
            'pear2\\windowsazure\\services\\blob\\models\\listblobsoptions' => '/WindowsAzure/Services/Blob/Models/ListBlobsOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\listblobsresult' => '/WindowsAzure/Services/Blob/Models/ListBlobsResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\listcontainersoptions' => '/WindowsAzure/Services/Blob/Models/ListContainersOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\listcontainersresult' => '/WindowsAzure/Services/Blob/Models/ListContainersResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\listpageblobrangesoptions' => '/WindowsAzure/Services/Blob/Models/ListPageBlobRangesOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\listpageblobrangesresult' => '/WindowsAzure/Services/Blob/Models/ListPageBlobRangesResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\pagerange' => '/WindowsAzure/Services/Blob/Models/PageRange.php',
            'pear2\\windowsazure\\services\\blob\\models\\pagewriteoption' => '/WindowsAzure/Services/Blob/Models/PageWriteOption.php',
            'pear2\\windowsazure\\services\\blob\\models\\publicaccesstype' => '/WindowsAzure/Services/Blob/Models/PublicAccessType.php',
            'pear2\\windowsazure\\services\\blob\\models\\setblobmetadataoptions' => '/WindowsAzure/Services/Blob/Models/SetBlobMetadataOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\setblobmetadataresult' => '/WindowsAzure/Services/Blob/Models/SetBlobMetadataResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\setblobpropertiesoptions' => '/WindowsAzure/Services/Blob/Models/SetBlobPropertiesOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\setblobpropertiesresult' => '/WindowsAzure/Services/Blob/Models/SetBlobPropertiesResult.php',
            'pear2\\windowsazure\\services\\blob\\models\\setcontainermetadataoptions' => '/WindowsAzure/Services/Blob/Models/SetContainerMetadataOptions.php',
            'pear2\\windowsazure\\services\\blob\\models\\signedidentifier' => '/WindowsAzure/Services/Blob/Models/SignedIdentifier.php',
            'pear2\\windowsazure\\services\\core\\authentication\\sharedkeyauthenticationscheme' => '/WindowsAzure/Services/Core/Authentication/SharedKeyAuthenticationScheme.php',
            'pear2\\windowsazure\\services\\core\\authentication\\storageauthenticationscheme' => '/WindowsAzure/Services/Core/Authentication/StorageAuthenticationScheme.php',
            'pear2\\windowsazure\\services\\core\\configuration' => '/WindowsAzure/Services/Core/Configuration.php',
            'pear2\\windowsazure\\services\\core\\filters\\datefilter' => '/WindowsAzure/Services/Core/Filters/DateFilter.php',
            'pear2\\windowsazure\\services\\core\\filters\\sharedkeyfilter' => '/WindowsAzure/Services/Core/Filters/SharedKeyFilter.php',
            'pear2\\windowsazure\\services\\core\\iservicebuilder' => '/WindowsAzure/Services/Core/IServiceBuilder.php',
            'pear2\\windowsazure\\services\\core\\models\\getservicepropertiesresult' => '/WindowsAzure/Services/Core/Models/GetServicePropertiesResult.php',
            'pear2\\windowsazure\\services\\core\\models\\logging' => '/WindowsAzure/Services/Core/Models/Logging.php',
            'pear2\\windowsazure\\services\\core\\models\\metrics' => '/WindowsAzure/Services/Core/Models/Metrics.php',
            'pear2\\windowsazure\\services\\core\\models\\retentionpolicy' => '/WindowsAzure/Services/Core/Models/RetentionPolicy.php',
            'pear2\\windowsazure\\services\\core\\models\\serviceproperties' => '/WindowsAzure/Services/Core/Models/ServiceProperties.php',
            'pear2\\windowsazure\\services\\core\\servicerestproxy' => '/WindowsAzure/Services/Core/ServiceRestProxy.php',
            'pear2\\windowsazure\\services\\core\\servicesbuilder' => '/WindowsAzure/Services/Core/ServicesBuilder.php',
            'pear2\\windowsazure\\services\\queue\\iqueue' => '/WindowsAzure/Services/Queue/IQueue.php',
            'pear2\\windowsazure\\services\\queue\\models\\createmessageoptions' => '/WindowsAzure/Services/Queue/Models/CreateMessageOptions.php',
            'pear2\\windowsazure\\services\\queue\\models\\createqueueoptions' => '/WindowsAzure/Services/Queue/Models/CreateQueueOptions.php',
            'pear2\\windowsazure\\services\\queue\\models\\getqueuemetadataresult' => '/WindowsAzure/Services/Queue/Models/GetQueueMetadataResult.php',
            'pear2\\windowsazure\\services\\queue\\models\\listmessagesoptions' => '/WindowsAzure/Services/Queue/Models/ListMessagesOptions.php',
            'pear2\\windowsazure\\services\\queue\\models\\listmessagesresult' => '/WindowsAzure/Services/Queue/Models/ListMessagesResult.php',
            'pear2\\windowsazure\\services\\queue\\models\\listqueuesoptions' => '/WindowsAzure/Services/Queue/Models/ListQueuesOptions.php',
            'pear2\\windowsazure\\services\\queue\\models\\listqueuesresult' => '/WindowsAzure/Services/Queue/Models/ListQueuesResult.php',
            'pear2\\windowsazure\\services\\queue\\models\\peekmessagesoptions' => '/WindowsAzure/Services/Queue/Models/PeekMessagesOptions.php',
            'pear2\\windowsazure\\services\\queue\\models\\peekmessagesresult' => '/WindowsAzure/Services/Queue/Models/PeekMessagesResult.php',
            'pear2\\windowsazure\\services\\queue\\models\\queue' => '/WindowsAzure/Services/Queue/Models/Queue.php',
            'pear2\\windowsazure\\services\\queue\\models\\queuemessage' => '/WindowsAzure/Services/Queue/Models/QueueMessage.php',
            'pear2\\windowsazure\\services\\queue\\models\\queueserviceoptions' => '/WindowsAzure/Services/Queue/Models/QueueServiceOptions.php',
            'pear2\\windowsazure\\services\\queue\\models\\updatemessageresult' => '/WindowsAzure/Services/Queue/Models/UpdateMessageResult.php',
            'pear2\\windowsazure\\services\\queue\\models\\windowsazurequeuemessage' => '/WindowsAzure/Services/Queue/Models/WindowsAzureQueueMessage.php',
            'pear2\\windowsazure\\services\\queue\\queuerestproxy' => '/WindowsAzure/Services/Queue/QueueRestProxy.php',
            'pear2\\windowsazure\\services\\queue\\queueservice' => '/WindowsAzure/Services/Queue/QueueService.php',
            'pear2\\windowsazure\\services\\queue\\queuesettings' => '/WindowsAzure/Services/Queue/QueueSettings.php',
            'pear2\\windowsazure\\utilities' => '/WindowsAzure/Utilities.php',
            'pear2\\windowsazure\\validate' => '/WindowsAzure/Validate.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
